import fs from 'fs';
import path from 'path';
import TurndownService from 'turndown';

/**
 * Storage Service
 * Handles file saving and organization
 */
export const storageService = {
  async save(data, format = 'json', baseRoot = './output') {
    const date = new Date().toISOString().split('T')[0];
    const shortTitle = this.sanitize(data.title || 'untitled');
    
    const targetPath = path.join(baseRoot, date, shortTitle);
    if (!fs.existsSync(targetPath)) fs.mkdirSync(targetPath, { recursive: true });
    
    const timestamp = Date.now();
    const fileName = `${shortTitle}_${timestamp}.${format}`;
    const filePath = path.join(targetPath, fileName);
    
    let content;
    switch (format.toLowerCase()) {
      case 'json':
        content = JSON.stringify(data, null, 2);
        break;
      case 'md':
      case 'markdown':
        content = this.toMarkdown(data);
        break;
      case 'txt':
        content = data.articleContent || data.transcript || data.title;
        break;
      default:
        content = JSON.stringify(data);
    }
    
    fs.writeFileSync(filePath, content);
    return filePath;
  },

  sanitize(text) {
    return text.toLowerCase().replace(/[^a-z0-9]/g, '-').substring(0, 30).replace(/-+/g, '-').replace(/-$/, '');
  },

  toMarkdown(data) {
    const turndown = new TurndownService();
    const body = data.articleContent || data.transcript || '';
    
    return `# ${data.title}
    
URL: ${data.url}
Author: ${data.author || 'Unknown'}
Published: ${data.publishedDate || 'Unknown'}
Extracted: ${data.extractedAt}

---

${body}

---
Generated by vidilearn CLI`;
  }
};